apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zx6fbrq7b-python 
  janus-idp.io/tekton: zx6fbrq7b-python
  backstage.io/kubernetes-id: zx6fbrq7b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zx6fbrq7b-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml